### ISSUE TITLE
django-redis 3.8 doc issue

### ISSUE THREAD

**Issue by khamaileon** [niwibe/django-redis#109]
Since raw_client has been removed, the following snippet is not working anymore.

How can we get the same result?

from django.core.cache import get_cache
django_redis = get_cache("default")  # Use the name you have defined for Redis in settings.CACHES
redis = django_redis.raw_client
connection_pool = redis.connection_pool
print("Created connections so far: %d" % connection_pool._created_connections)

**Comment by niwibe** [comment]
Fixed!

**Comment by khamaileon** [comment]
Thank you :)
