### ISSUE TITLE
Add `SOCKET_CONNECT_TIMEOUT` option?

### ISSUE THREAD

**Issue by jorgecarleitao** [niwibe/django-redis#116]
Redis.py 2.10 allows to distinguish between a socket timeout and a timeout on read/write, e.g. see [here](https://github.com/andymccurdy/redis-py/issues/485).

We could support this in the connection options, with an implementation similar to `SOCKET_TIMEOUT`.

If you agree on this, I can PR it.

**Comment by niwibe** [comment]
+1
