### ISSUE TITLE
sentinel.py file missing

### ISSUE THREAD

**Issue by arafiq** [niwibe/django-redis#119]
I am looking at https://github.com/niwibe/django-redis/blob/master/redis_cache/client/sentinel.py file amd it points to another file that does not exist (django-redis/redis_cache/client/sentinel.py).  I want to test out the sentinel plugin but the file seems to be missing, or am I missing the something. I thank you in advance for the response.

**Comment by niwibe** [comment]
This is a bug. The sentinel support was removed in the last version. Because I can not use it and I not will be able dedicate time for maintain that code.

The code is available in previous versions (see tags) and maybe the best approach for sentinel plugin is live in a separate package.

**Comment by arafiq** [comment]
understood. Thank you for your reply.

**Comment by niwibe** [comment]
Now all the redis_cache directory tree is removed because it was deprecated ;)
