### ISSUE TITLE
0 timeout in Django means expire immediately, not cache forever

### ISSUE THREAD

**Issue by AlexHill** [niwibe/django-redis#127]
django-redis interprets both ``None`` and ``0`` as infinite timeouts. This departs from the convention throughout Django's cache system, where ``None`` means cache forever, but ``0`` means expire immediately:

From the [cache API basic usage docs](https://docs.djangoproject.com/en/1.8/topics/cache/#basic-usage):
> Passing in None for timeout will cache the value forever. A timeout of 0 won’t cache the value.

From the [section on the ``TIMEOUT`` cache setting](https://docs.djangoproject.com/en/1.8/topics/cache/#cache-arguments):
> You can set TIMEOUT to None so that, by default, cache keys never expire. A value of 0 causes keys to immediately expire (effectively “don’t cache”).

Would you consider changing django-redis to fall in line with this style?

**Comment by niwibe** [comment]
This can be a big backward incompatibility, but seems reasonable for 4.0.0

**Comment by niwibe** [comment]
Already commited in master.

**Comment by AlexHill** [comment]
Thanks!
